name: E2E Build Android

on:
  workflow_call:
    secrets:
      EXPERIMENTAL_KEYSTORE_BASE64:
        required: true
      EXPERIMENTAL_KEYSTORE_PASSWORD:
        required: true
      EXPERIMENTAL_KEY_ALIAS:
        required: true
      EXPERIMENTAL_KEY_PASSWORD:
        required: true
      BUGSNAG_KEY:
        required: true

jobs:
  android-build:
    runs-on: ubuntu-latest

    outputs:
      artifact_name: Android Experimental APK

    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4

      - name: Checkout and Setup Node
        uses: ./.github/actions/setup-node

      - name: Setup E2E Account
        uses: ./.github/actions/e2e-account
        with:
          E2E_ACCOUNT: ${{ secrets.E2E_ACCOUNT }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches/modules-2
            ~/.gradle/caches/transforms-*
            ~/.gradle/caches/build-cache-*
          key: gradle-transforms-v1-${{ runner.os }}-${{ hashFiles('**/*.gradle*', 'gradle-wrapper.properties') }}
          restore-keys: |
            gradle-transforms-v1-${{ runner.os }}-

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'none'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          cache-disabled: true

      - name: Decode Keystore
        run: |
          echo "${{ secrets.EXPERIMENTAL_KEYSTORE_BASE64 }}" | base64 -d > android/app/release.keystore

      - name: Set gradle.properties
        run: |
          echo " " >> android/gradle.properties
          echo "KEYSTORE=release.keystore" >> android/gradle.properties
          echo "KEYSTORE_PASSWORD=${{ secrets.EXPERIMENTAL_KEYSTORE_PASSWORD }}" >> android/gradle.properties
          echo "KEY_ALIAS=${{ secrets.EXPERIMENTAL_KEY_ALIAS }}" >> android/gradle.properties
          echo "KEY_PASSWORD=${{ secrets.EXPERIMENTAL_KEY_PASSWORD }}" >> android/gradle.properties
          echo "BugsnagAPIKey=${{ secrets.BUGSNAG_KEY }}" >> android/gradle.properties
          
      - name: Build Android Release APK
        working-directory: android
        run: ./gradlew assembleExperimentalRelease --build-cache --parallel --max-workers=4 --no-daemon --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android Experimental APK
          path: android/app/build/outputs/apk/experimental/release/app-experimental-release.apk