name: Maestro Tests on Android

on:
  workflow_call:
    inputs:
      shard:
        required: true
        type: string

jobs:
  android-test:
    name: 'Android Tests'
    runs-on: ubuntu-latest
    env:
      MAESTRO_VERSION: 2.2.0

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Android AVD
        uses: actions/cache@v4
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ runner.os }}-api34

      - name: Cache Maestro
        uses: actions/cache@v4
        with:
          path: ~/.maestro
          key: maestro-${{ runner.os }}-${{ env.MAESTRO_VERSION }}

      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: Android Experimental APK

      - name: Setup E2E Account
        uses: ./.github/actions/e2e-account
        with:
          E2E_ACCOUNT: ${{ secrets.E2E_ACCOUNT }}

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> "$GITHUB_PATH"

      - name: Enable KVM group permissions
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Disable unnecessary services (improves emulator stability)
        run: |
          sudo systemctl stop docker || true
          sudo systemctl stop snapd || true

      - name: Make Maestro script executable
        run: chmod +x .github/scripts/run-maestro.sh

      - name: Start Android Emulator and Run Maestro Tests
        uses: reactivecircus/android-emulator-runner@v2
        timeout-minutes: 60
        with:
          api-level: 34
          disk-size: 4096M
          arch: x86_64
          target: google_apis
          profile: pixel_7_pro
          cores: 4
          ram-size: 4096M
          force-avd-creation: false
          disable-animations: true
          emulator-boot-timeout: 900
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -accel on
          script: ./.github/scripts/run-maestro.sh android ${{ inputs.shard }}

      - name: Android Maestro Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Android Maestro Logs - Shard ${{ inputs.shard }}
          path: ~/.maestro/tests/**/*.png
          retention-days: 7
